import "./globals.css";
import Navbar from "@/components/NavbarComponent/Navbar";
import Loading from "./loading";

export const metadata = {
  title: "JudgeNot0 | An Online Judge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
