name: Feature Request
description: Suggest a new feature for the judge-not-zero MVP
title: '[Feature] judge-not-zero - Brief title'
labels: ['enhancement', 'mvp']
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Description Template
        Use this form to propose a new feature for the judge-not-zero MVP. Provide clear details to help prioritize and implement it.
  - type: textarea
    id: problem-need
    attributes:
      label: Problem/Need
      description: What user pain point does this solve?
      placeholder: e.g., "Manual code judging is slow and error-prone"
      value: ""
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe what the feature should do and include a user story.
      placeholder: |
        High-level: e.g., "Automated judging with microservices"
        User Story: As a [user type], I want [feature] so that [benefit].
      value: ""
    validations:
      required: true
  - type: textarea
    id: detailed-specs
    attributes:
      label: Detailed Specs
      description: Provide technical details for the feature.
      placeholder: |
        - Inputs/Outputs: e.g., "Input: CLI command; Output: Scaffolded folder."
        - Edge Cases: e.g., "Handle multiple languages."
        - Tech Stack: e.g., "Next.js, Go, PostgreSQL"
      value: ""
    validations:
      required: false
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List measurable criteria for feature completion.
      placeholder: |
        - [ ] e.g., "Works on Web; <5s execution."
        - [ ] e.g., "Tested with sample data."
        - [ ] e.g., "Docs updated in README."
      value: ""
    validations:
      required: false
  - type: dropdown
    id: mvp-priority
    attributes:
      label: MVP Fit & Priority
      description: How critical is this feature for the MVP?
      options:
        - Must-Have (v0.1)
        - Should-Have (Post-MVP)
        - Could-Have (Nice-to-Have)
        - Won't-Have (Out of Scope)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: effort
    attributes:
      label: Effort Estimate
      description: Estimated effort to implement the feature.
      options:
        - Low (1-2 days)
        - Medium (3-7 days)
        - High (1-2 weeks)
        - Very High (2+ weeks)
      default: 0
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches considered?
      placeholder: e.g., "Manual vs. automated approach."
      value: ""
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add screenshots, wireframes, or related issue references.
      placeholder: Related Issues: [#123]
      value: ""
    validations:
      required: false